# Generated by Django 5.2.1 on 2025-05-10 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='guard',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'guard'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesspasses',
            name='devices',
            field=models.ManyToManyField(blank=True, to='core.devices'),
        ),
        migrations.AddField(
            model_name='accesslogs',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.devices'),
        ),
        migrations.AddField(
            model_name='facilities',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devices',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facilities'),
        ),
        migrations.AddField(
            model_name='accesspasses',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facilities'),
        ),
    ]
