# Generated by Django 5.2.1 on 2025-05-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslogs',
            options={'verbose_name': 'Лог пропуска', 'verbose_name_plural': 'Логи пропусков'},
        ),
        migrations.AlterModelOptions(
            name='accesspasses',
            options={'verbose_name': 'Пропуск', 'verbose_name_plural': 'Пропуски'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': 'Турникет', 'verbose_name_plural': 'Турникеты'},
        ),
        migrations.AlterModelOptions(
            name='facilities',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.RemoveField(
            model_name='devices',
            name='guard',
        ),
    ]
