# Generated by Django 5.2.1 on 2025-05-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_accesslogs_options_alter_accesspasses_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspasses',
            name='photo',
        ),
        migrations.AlterField(
            model_name='accesslogs',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
