# Generated by Django 5.2.1 on 2025-05-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_accesspasses_photo_alter_accesslogs_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspasses',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
