# Generated by Django 5.2.1 on 2025-05-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_accesspasses_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspasses',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
