# Generated by Django 5.2.1 on 2025-05-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'verbose_name': 'Приглашение на регистрацию', 'verbose_name_plural': 'Приглашения на регистрацию'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Суперадмин'), ('admin', 'Администратор объекта'), ('technician', 'Техник')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Суперадмин'), ('admin', 'Администратор объекта'), ('technician', 'Техник')], max_length=20),
        ),
    ]
