# Generated by Django 5.2.1 on 2025-05-22 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_accesspasses_options_and_more'),
        ('users', '0002_alter_invite_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facilities', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Суперадмин'), ('admin', 'Администратор объекта'), ('technician', 'Техник')], max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(max_length=64, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Использовано'),
        ),
    ]
